Update README.md
layer5io/service-mesh-labs pull request #20
Opened 2021-07-01 13:53 UTC by Patil2099

Fixes #19

2021-07-03 11:04 UTC, includestdlibrary requested changes
Thanks @Patil2099 for the PR. 
Here are some instructions to make sure that your commits are signed off- https://github.com/layer5io/service-mesh-labs/pull/20/checks

2021-07-06 13:28 UTC, amino19 commented on README.md
> +✔️ <em><strong>Access</strong></em> the <a href="https://drive.google.com/drive/u/4/folders/0ABH8aabN4WAKUk9PVA">community drive</a>.<br />\
@Patil2099 : The slash `\` at last, need to be remove that, & please signed-off your commits :slightly_smiling_face: 

& yeah, you're good to go :rocket:

2021-07-07 05:12 UTC, leecalcote commented
@Patil2099 checking in... will you be returning to amend your commit with a sign-off?

2021-07-30 23:52 UTC, leecalcote commented on README.md
> +✔️ <em><strong>Access</strong></em> the <a href="https://drive.google.com/drive/u/4/folders/0ABH8aabN4WAKUk9PVA">community drive</a>.<br />\
```suggestion
✔️ <em><strong>Access</strong></em> the <a href="https://drive.google.com/drive/u/4/folders/0ABH8aabN4WAKUk9PVA">community drive</a>.<br />
```

2021-07-30 23:53 UTC, leecalcote approved these changes
Thank you, @amino19. I remove the backslash.

2021-07-30 23:53 UTC, merged