Updating Figma Open Invite Link in Docs
layer5io/service-mesh-labs pull request #71
Opened 2023-07-13 17:36 UTC by JapneetRajput

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ x] Yes, I signed my commits.

2023-07-18 15:37 UTC, thisiskaransgit requested changes

2023-07-18 15:37 UTC, thisiskaransgit commented on .github/ISSUE_TEMPLATE/documentation.md
> +- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```suggestion
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

```

2023-07-18 15:37 UTC, thisiskaransgit commented on .github/ISSUE_TEMPLATE/documentation.md
> +- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
@JapneetRajput, kindly do the same update in the other file too.

2023-07-22 19:41 UTC, abhijeetgauravm commented
Can u assign me?

2023-12-15 06:04 UTC, closed without merging